spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    sql: debug
    web: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false