spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    sql: debug
    web: debug